Clock cpp
franchiStud/exercises pull request #5
Opened 2022-07-19 08:45 UTC by franchiStud

2022-07-20 15:42 UTC, lucaotta requested changes
Stiamo arrivando in fondo, benissimo! Ti ho indicato alcune migliorie che si possono applicare, fammi sapere se ti torna tutto.

2022-07-20 15:42 UTC, lucaotta commented on Clock/timervalues.h
> +    void drainTime();
`drainTime()` come `public slots` mi lascia perplesso: lo chiami anche dal QML? Se è una funzione interna la puoi lasciare come `private` o al limite `private slots`.

2022-07-20 15:42 UTC, lucaotta commented on Clock/timervalues.cpp
> +    isTimerRunning=true;
Per non sbagliare, potresti creare un setter privato per queste variabili che ti emette il segnale solo se sono cambiate. È anche la cosa giusta perché ti aiutano ad evitare i binding loops, una cosa brutta. Il codice è qualcosa del genere:
```c++
void setIsThereTimer(bool val) {
  if (isThereTimer != val) {
    isThereTimer = val;
    emit isThereTimerChanged();
  }
}
```
Va bene lasciarlo privato e non metterlo come WRITE nella property.

2022-07-20 15:42 UTC, lucaotta commented on Clock/timervalues.cpp
> +    leftHours=startHours;
Qua ti mancano tutti i setter, come spiegato sopra.

2022-07-20 15:42 UTC, lucaotta commented on Clock/date.h
> +public slots:
Metti `refresh` come private o private slots.

2022-07-20 15:42 UTC, lucaotta commented on Clock/date.h
> +    Q_PROPERTY(QDateTime date MEMBER date NOTIFY onDateChanged)
Qua togli il MEMBER e usa solo READ, altrimenti da QML puoi modificare questa property, cosa che non vogliamo fare.

2022-07-20 15:42 UTC, lucaotta commented on Clock/boolcontrols.h
> +    Q_PROPERTY(int  activeAlarms   MEMBER activeAlarms   NOTIFY onActiveAlarmsChanged)
Anche qua togli il MEMBER e usa READ

2022-07-20 15:42 UTC, lucaotta commented on Clock/ViewTimerSet.qml
> +            timerValues.isThereTimer=true;
`isThereTimer` lo deve modificare `timerValues` al suo interno quando lanci `start()`. In questo modo sposti la logica in C++ invece che averla nella UI.

2022-07-20 15:42 UTC, lucaotta commented on Clock/ViewTimerSet.qml
> +            timerValues.isThereTimer=true;
Pensa sempre che potresti per qualche ragione far partire il timer da qualche altra parte, poi ti devi ricordare di impostare `isThereTimer` anche di là...

2022-07-20 15:42 UTC, lucaotta commented on Clock/ViewAlarmSet.qml
> +            controls.isThereAlarm=true
Anche questo probabilmente dovrebbe essere gestito automaticamente da `controls`, come pure l'incremento di `activeAlarms` poco più sotto

2022-07-20 15:42 UTC, lucaotta commented on Clock/DigitalClock.qml
> +                     : Qt.formatDateTime(currentDate.date, "hh:mm AP").replace("AM","")
Non ho capito perché devi fare una replace sulla stringa formattata...non ti basta togliere `AP` dal formato?

2022-07-21 07:49 UTC, franchiStud commented on Clock/DigitalClock.qml
> +                     : Qt.formatDateTime(currentDate.date, "hh:mm AP").replace("AM","")
se tolgo `AP` dal formato Qt.formatDateTime mi restituisce l'orario su base 24 ore, e per come è impostato il programma ho bisogno di valori da 0 a 12

2022-07-21 10:32 UTC, lucaotta approved these changes
Ti lascio solo da modificare una property in `READ` e poi possiamo mergiare!

2022-07-21 10:32 UTC, lucaotta commented on Clock/alarm.h
> +    Q_PROPERTY(int  activeAlarms   MEMBER activeAlarms   NOTIFY onActiveAlarmsChanged)
Come dicevamo, queste property è meglio che siano solo READ e non MEMBER

2022-07-21 10:32 UTC, lucaotta commented on Clock/main.qml
> +                    var alarmsToDelete=alarmList.isSelected.length;
Il posto giusto dove fare tutte queste cose sarebbe il C++, altrimenti hai troppa logica nella parte di grafica. Sarà per la prossima volta! :)

2022-07-21 10:49 UTC, merged